// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package com.sumscope.qt.cbt.connector.ufx.protobuf.entity;

public final class SubscribeReq {
  private SubscribeReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BankMtkRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BankMtkRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 账户编号
     * </pre>
     *
     * <code>string account_code = 1;</code>
     * @return The accountCode.
     */
    java.lang.String getAccountCode();
    /**
     * <pre>
     **
     * 账户编号
     * </pre>
     *
     * <code>string account_code = 1;</code>
     * @return The bytes for accountCode.
     */
    com.google.protobuf.ByteString
        getAccountCodeBytes();

    /**
     * <pre>
     **
     *组合编号
     * </pre>
     *
     * <code>string combi_no = 2;</code>
     * @return The combiNo.
     */
    java.lang.String getCombiNo();
    /**
     * <pre>
     **
     *组合编号
     * </pre>
     *
     * <code>string combi_no = 2;</code>
     * @return The bytes for combiNo.
     */
    com.google.protobuf.ByteString
        getCombiNoBytes();

    /**
     * <pre>
     **
     * 投资类型
     * </pre>
     *
     * <code>string invest_type = 3;</code>
     * @return The investType.
     */
    java.lang.String getInvestType();
    /**
     * <pre>
     **
     * 投资类型
     * </pre>
     *
     * <code>string invest_type = 3;</code>
     * @return The bytes for investType.
     */
    com.google.protobuf.ByteString
        getInvestTypeBytes();

    /**
     * <pre>
     **
     * 请求编号
     * </pre>
     *
     * <code>string request_id = 4;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     **
     * 请求编号
     * </pre>
     *
     * <code>string request_id = 4;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     **
     * 本方交易员
     * </pre>
     *
     * <code>string owner_operator_name = 5;</code>
     * @return The ownerOperatorName.
     */
    java.lang.String getOwnerOperatorName();
    /**
     * <pre>
     **
     * 本方交易员
     * </pre>
     *
     * <code>string owner_operator_name = 5;</code>
     * @return The bytes for ownerOperatorName.
     */
    com.google.protobuf.ByteString
        getOwnerOperatorNameBytes();

    /**
     * <pre>
     **
     *净价
     * </pre>
     *
     * <code>double net_price = 6;</code>
     * @return The netPrice.
     */
    double getNetPrice();

    /**
     * <pre>
     **
     * 券面总额
     * </pre>
     *
     * <code>double face_balance = 7;</code>
     * @return The faceBalance.
     */
    double getFaceBalance();

    /**
     * <pre>
     **
     * 有效时间
     * </pre>
     *
     * <code>int32 valid_time = 8;</code>
     * @return Whether the validTime field is set.
     */
    boolean hasValidTime();
    /**
     * <pre>
     **
     * 有效时间
     * </pre>
     *
     * <code>int32 valid_time = 8;</code>
     * @return The validTime.
     */
    int getValidTime();

    /**
     * <pre>
     **
     * 第三方系统自定义号
     * </pre>
     *
     * <code>int32 extsystem_id = 9;</code>
     * @return Whether the extsystemId field is set.
     */
    boolean hasExtsystemId();
    /**
     * <pre>
     **
     * 第三方系统自定义号
     * </pre>
     *
     * <code>int32 extsystem_id = 9;</code>
     * @return The extsystemId.
     */
    int getExtsystemId();

    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 10;</code>
     * @return Whether the thirdReff field is set.
     */
    boolean hasThirdReff();
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 10;</code>
     * @return The thirdReff.
     */
    java.lang.String getThirdReff();
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 10;</code>
     * @return The bytes for thirdReff.
     */
    com.google.protobuf.ByteString
        getThirdReffBytes();
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code BankMtkRequest}
   */
  public static final class BankMtkRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BankMtkRequest)
      BankMtkRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BankMtkRequest.newBuilder() to construct.
    private BankMtkRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BankMtkRequest() {
      accountCode_ = "";
      combiNo_ = "";
      investType_ = "";
      requestId_ = "";
      ownerOperatorName_ = "";
      thirdReff_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BankMtkRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BankMtkRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              accountCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              combiNo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              investType_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              ownerOperatorName_ = s;
              break;
            }
            case 49: {

              netPrice_ = input.readDouble();
              break;
            }
            case 57: {

              faceBalance_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000001;
              validTime_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000002;
              extsystemId_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              thirdReff_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscribeReq.internal_static_BankMtkRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscribeReq.internal_static_BankMtkRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeReq.BankMtkRequest.class, SubscribeReq.BankMtkRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ACCOUNT_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object accountCode_;
    /**
     * <pre>
     **
     * 账户编号
     * </pre>
     *
     * <code>string account_code = 1;</code>
     * @return The accountCode.
     */
    @java.lang.Override
    public java.lang.String getAccountCode() {
      java.lang.Object ref = accountCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 账户编号
     * </pre>
     *
     * <code>string account_code = 1;</code>
     * @return The bytes for accountCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountCodeBytes() {
      java.lang.Object ref = accountCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMBI_NO_FIELD_NUMBER = 2;
    private volatile java.lang.Object combiNo_;
    /**
     * <pre>
     **
     *组合编号
     * </pre>
     *
     * <code>string combi_no = 2;</code>
     * @return The combiNo.
     */
    @java.lang.Override
    public java.lang.String getCombiNo() {
      java.lang.Object ref = combiNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        combiNo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     *组合编号
     * </pre>
     *
     * <code>string combi_no = 2;</code>
     * @return The bytes for combiNo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCombiNoBytes() {
      java.lang.Object ref = combiNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        combiNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INVEST_TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object investType_;
    /**
     * <pre>
     **
     * 投资类型
     * </pre>
     *
     * <code>string invest_type = 3;</code>
     * @return The investType.
     */
    @java.lang.Override
    public java.lang.String getInvestType() {
      java.lang.Object ref = investType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        investType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 投资类型
     * </pre>
     *
     * <code>string invest_type = 3;</code>
     * @return The bytes for investType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInvestTypeBytes() {
      java.lang.Object ref = investType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        investType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object requestId_;
    /**
     * <pre>
     **
     * 请求编号
     * </pre>
     *
     * <code>string request_id = 4;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 请求编号
     * </pre>
     *
     * <code>string request_id = 4;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_OPERATOR_NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object ownerOperatorName_;
    /**
     * <pre>
     **
     * 本方交易员
     * </pre>
     *
     * <code>string owner_operator_name = 5;</code>
     * @return The ownerOperatorName.
     */
    @java.lang.Override
    public java.lang.String getOwnerOperatorName() {
      java.lang.Object ref = ownerOperatorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerOperatorName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 本方交易员
     * </pre>
     *
     * <code>string owner_operator_name = 5;</code>
     * @return The bytes for ownerOperatorName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerOperatorNameBytes() {
      java.lang.Object ref = ownerOperatorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerOperatorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NET_PRICE_FIELD_NUMBER = 6;
    private double netPrice_;
    /**
     * <pre>
     **
     *净价
     * </pre>
     *
     * <code>double net_price = 6;</code>
     * @return The netPrice.
     */
    @java.lang.Override
    public double getNetPrice() {
      return netPrice_;
    }

    public static final int FACE_BALANCE_FIELD_NUMBER = 7;
    private double faceBalance_;
    /**
     * <pre>
     **
     * 券面总额
     * </pre>
     *
     * <code>double face_balance = 7;</code>
     * @return The faceBalance.
     */
    @java.lang.Override
    public double getFaceBalance() {
      return faceBalance_;
    }

    public static final int VALID_TIME_FIELD_NUMBER = 8;
    private int validTime_;
    /**
     * <pre>
     **
     * 有效时间
     * </pre>
     *
     * <code>int32 valid_time = 8;</code>
     * @return Whether the validTime field is set.
     */
    @java.lang.Override
    public boolean hasValidTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     **
     * 有效时间
     * </pre>
     *
     * <code>int32 valid_time = 8;</code>
     * @return The validTime.
     */
    @java.lang.Override
    public int getValidTime() {
      return validTime_;
    }

    public static final int EXTSYSTEM_ID_FIELD_NUMBER = 9;
    private int extsystemId_;
    /**
     * <pre>
     **
     * 第三方系统自定义号
     * </pre>
     *
     * <code>int32 extsystem_id = 9;</code>
     * @return Whether the extsystemId field is set.
     */
    @java.lang.Override
    public boolean hasExtsystemId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     **
     * 第三方系统自定义号
     * </pre>
     *
     * <code>int32 extsystem_id = 9;</code>
     * @return The extsystemId.
     */
    @java.lang.Override
    public int getExtsystemId() {
      return extsystemId_;
    }

    public static final int THIRD_REFF_FIELD_NUMBER = 10;
    private volatile java.lang.Object thirdReff_;
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 10;</code>
     * @return Whether the thirdReff field is set.
     */
    @java.lang.Override
    public boolean hasThirdReff() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 10;</code>
     * @return The thirdReff.
     */
    @java.lang.Override
    public java.lang.String getThirdReff() {
      java.lang.Object ref = thirdReff_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        thirdReff_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 10;</code>
     * @return The bytes for thirdReff.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThirdReffBytes() {
      java.lang.Object ref = thirdReff_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thirdReff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountCode_);
      }
      if (!getCombiNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, combiNo_);
      }
      if (!getInvestTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, investType_);
      }
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, requestId_);
      }
      if (!getOwnerOperatorNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ownerOperatorName_);
      }
      if (netPrice_ != 0D) {
        output.writeDouble(6, netPrice_);
      }
      if (faceBalance_ != 0D) {
        output.writeDouble(7, faceBalance_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(8, validTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(9, extsystemId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, thirdReff_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountCode_);
      }
      if (!getCombiNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, combiNo_);
      }
      if (!getInvestTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, investType_);
      }
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, requestId_);
      }
      if (!getOwnerOperatorNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ownerOperatorName_);
      }
      if (netPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, netPrice_);
      }
      if (faceBalance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, faceBalance_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, validTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, extsystemId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, thirdReff_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SubscribeReq.BankMtkRequest)) {
        return super.equals(obj);
      }
      SubscribeReq.BankMtkRequest other = (SubscribeReq.BankMtkRequest) obj;

      if (!getAccountCode()
          .equals(other.getAccountCode())) return false;
      if (!getCombiNo()
          .equals(other.getCombiNo())) return false;
      if (!getInvestType()
          .equals(other.getInvestType())) return false;
      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (!getOwnerOperatorName()
          .equals(other.getOwnerOperatorName())) return false;
      if (java.lang.Double.doubleToLongBits(getNetPrice())
          != java.lang.Double.doubleToLongBits(
              other.getNetPrice())) return false;
      if (java.lang.Double.doubleToLongBits(getFaceBalance())
          != java.lang.Double.doubleToLongBits(
              other.getFaceBalance())) return false;
      if (hasValidTime() != other.hasValidTime()) return false;
      if (hasValidTime()) {
        if (getValidTime()
            != other.getValidTime()) return false;
      }
      if (hasExtsystemId() != other.hasExtsystemId()) return false;
      if (hasExtsystemId()) {
        if (getExtsystemId()
            != other.getExtsystemId()) return false;
      }
      if (hasThirdReff() != other.hasThirdReff()) return false;
      if (hasThirdReff()) {
        if (!getThirdReff()
            .equals(other.getThirdReff())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAccountCode().hashCode();
      hash = (37 * hash) + COMBI_NO_FIELD_NUMBER;
      hash = (53 * hash) + getCombiNo().hashCode();
      hash = (37 * hash) + INVEST_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getInvestType().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + OWNER_OPERATOR_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerOperatorName().hashCode();
      hash = (37 * hash) + NET_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNetPrice()));
      hash = (37 * hash) + FACE_BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFaceBalance()));
      if (hasValidTime()) {
        hash = (37 * hash) + VALID_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getValidTime();
      }
      if (hasExtsystemId()) {
        hash = (37 * hash) + EXTSYSTEM_ID_FIELD_NUMBER;
        hash = (53 * hash) + getExtsystemId();
      }
      if (hasThirdReff()) {
        hash = (37 * hash) + THIRD_REFF_FIELD_NUMBER;
        hash = (53 * hash) + getThirdReff().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SubscribeReq.BankMtkRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscribeReq.BankMtkRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SubscribeReq.BankMtkRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscribeReq.BankMtkRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SubscribeReq.BankMtkRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * </pre>
     *
     * Protobuf type {@code BankMtkRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BankMtkRequest)
        SubscribeReq.BankMtkRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscribeReq.internal_static_BankMtkRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscribeReq.internal_static_BankMtkRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscribeReq.BankMtkRequest.class, SubscribeReq.BankMtkRequest.Builder.class);
      }

      // Construct using com.sumscope.qt.cbt.connector.ufx.protobuf.entity.SubscribeReq.BankMtkRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accountCode_ = "";

        combiNo_ = "";

        investType_ = "";

        requestId_ = "";

        ownerOperatorName_ = "";

        netPrice_ = 0D;

        faceBalance_ = 0D;

        validTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        extsystemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        thirdReff_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscribeReq.internal_static_BankMtkRequest_descriptor;
      }

      @java.lang.Override
      public SubscribeReq.BankMtkRequest getDefaultInstanceForType() {
        return SubscribeReq.BankMtkRequest.getDefaultInstance();
      }

      @java.lang.Override
      public SubscribeReq.BankMtkRequest build() {
        SubscribeReq.BankMtkRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SubscribeReq.BankMtkRequest buildPartial() {
        SubscribeReq.BankMtkRequest result = new SubscribeReq.BankMtkRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.accountCode_ = accountCode_;
        result.combiNo_ = combiNo_;
        result.investType_ = investType_;
        result.requestId_ = requestId_;
        result.ownerOperatorName_ = ownerOperatorName_;
        result.netPrice_ = netPrice_;
        result.faceBalance_ = faceBalance_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.validTime_ = validTime_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.extsystemId_ = extsystemId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.thirdReff_ = thirdReff_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SubscribeReq.BankMtkRequest) {
          return mergeFrom((SubscribeReq.BankMtkRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SubscribeReq.BankMtkRequest other) {
        if (other == SubscribeReq.BankMtkRequest.getDefaultInstance()) return this;
        if (!other.getAccountCode().isEmpty()) {
          accountCode_ = other.accountCode_;
          onChanged();
        }
        if (!other.getCombiNo().isEmpty()) {
          combiNo_ = other.combiNo_;
          onChanged();
        }
        if (!other.getInvestType().isEmpty()) {
          investType_ = other.investType_;
          onChanged();
        }
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (!other.getOwnerOperatorName().isEmpty()) {
          ownerOperatorName_ = other.ownerOperatorName_;
          onChanged();
        }
        if (other.getNetPrice() != 0D) {
          setNetPrice(other.getNetPrice());
        }
        if (other.getFaceBalance() != 0D) {
          setFaceBalance(other.getFaceBalance());
        }
        if (other.hasValidTime()) {
          setValidTime(other.getValidTime());
        }
        if (other.hasExtsystemId()) {
          setExtsystemId(other.getExtsystemId());
        }
        if (other.hasThirdReff()) {
          bitField0_ |= 0x00000004;
          thirdReff_ = other.thirdReff_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SubscribeReq.BankMtkRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SubscribeReq.BankMtkRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object accountCode_ = "";
      /**
       * <pre>
       **
       * 账户编号
       * </pre>
       *
       * <code>string account_code = 1;</code>
       * @return The accountCode.
       */
      public java.lang.String getAccountCode() {
        java.lang.Object ref = accountCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 账户编号
       * </pre>
       *
       * <code>string account_code = 1;</code>
       * @return The bytes for accountCode.
       */
      public com.google.protobuf.ByteString
          getAccountCodeBytes() {
        java.lang.Object ref = accountCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 账户编号
       * </pre>
       *
       * <code>string account_code = 1;</code>
       * @param value The accountCode to set.
       * @return This builder for chaining.
       */
      public Builder setAccountCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 账户编号
       * </pre>
       *
       * <code>string account_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountCode() {
        
        accountCode_ = getDefaultInstance().getAccountCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 账户编号
       * </pre>
       *
       * <code>string account_code = 1;</code>
       * @param value The bytes for accountCode to set.
       * @return This builder for chaining.
       */
      public Builder setAccountCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object combiNo_ = "";
      /**
       * <pre>
       **
       *组合编号
       * </pre>
       *
       * <code>string combi_no = 2;</code>
       * @return The combiNo.
       */
      public java.lang.String getCombiNo() {
        java.lang.Object ref = combiNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          combiNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       *组合编号
       * </pre>
       *
       * <code>string combi_no = 2;</code>
       * @return The bytes for combiNo.
       */
      public com.google.protobuf.ByteString
          getCombiNoBytes() {
        java.lang.Object ref = combiNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          combiNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       *组合编号
       * </pre>
       *
       * <code>string combi_no = 2;</code>
       * @param value The combiNo to set.
       * @return This builder for chaining.
       */
      public Builder setCombiNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        combiNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *组合编号
       * </pre>
       *
       * <code>string combi_no = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCombiNo() {
        
        combiNo_ = getDefaultInstance().getCombiNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *组合编号
       * </pre>
       *
       * <code>string combi_no = 2;</code>
       * @param value The bytes for combiNo to set.
       * @return This builder for chaining.
       */
      public Builder setCombiNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        combiNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object investType_ = "";
      /**
       * <pre>
       **
       * 投资类型
       * </pre>
       *
       * <code>string invest_type = 3;</code>
       * @return The investType.
       */
      public java.lang.String getInvestType() {
        java.lang.Object ref = investType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          investType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 投资类型
       * </pre>
       *
       * <code>string invest_type = 3;</code>
       * @return The bytes for investType.
       */
      public com.google.protobuf.ByteString
          getInvestTypeBytes() {
        java.lang.Object ref = investType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          investType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 投资类型
       * </pre>
       *
       * <code>string invest_type = 3;</code>
       * @param value The investType to set.
       * @return This builder for chaining.
       */
      public Builder setInvestType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        investType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 投资类型
       * </pre>
       *
       * <code>string invest_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInvestType() {
        
        investType_ = getDefaultInstance().getInvestType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 投资类型
       * </pre>
       *
       * <code>string invest_type = 3;</code>
       * @param value The bytes for investType to set.
       * @return This builder for chaining.
       */
      public Builder setInvestTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        investType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       **
       * 请求编号
       * </pre>
       *
       * <code>string request_id = 4;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 请求编号
       * </pre>
       *
       * <code>string request_id = 4;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 请求编号
       * </pre>
       *
       * <code>string request_id = 4;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 请求编号
       * </pre>
       *
       * <code>string request_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 请求编号
       * </pre>
       *
       * <code>string request_id = 4;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ownerOperatorName_ = "";
      /**
       * <pre>
       **
       * 本方交易员
       * </pre>
       *
       * <code>string owner_operator_name = 5;</code>
       * @return The ownerOperatorName.
       */
      public java.lang.String getOwnerOperatorName() {
        java.lang.Object ref = ownerOperatorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ownerOperatorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 本方交易员
       * </pre>
       *
       * <code>string owner_operator_name = 5;</code>
       * @return The bytes for ownerOperatorName.
       */
      public com.google.protobuf.ByteString
          getOwnerOperatorNameBytes() {
        java.lang.Object ref = ownerOperatorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ownerOperatorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 本方交易员
       * </pre>
       *
       * <code>string owner_operator_name = 5;</code>
       * @param value The ownerOperatorName to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerOperatorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerOperatorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 本方交易员
       * </pre>
       *
       * <code>string owner_operator_name = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerOperatorName() {
        
        ownerOperatorName_ = getDefaultInstance().getOwnerOperatorName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 本方交易员
       * </pre>
       *
       * <code>string owner_operator_name = 5;</code>
       * @param value The bytes for ownerOperatorName to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerOperatorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ownerOperatorName_ = value;
        onChanged();
        return this;
      }

      private double netPrice_ ;
      /**
       * <pre>
       **
       *净价
       * </pre>
       *
       * <code>double net_price = 6;</code>
       * @return The netPrice.
       */
      @java.lang.Override
      public double getNetPrice() {
        return netPrice_;
      }
      /**
       * <pre>
       **
       *净价
       * </pre>
       *
       * <code>double net_price = 6;</code>
       * @param value The netPrice to set.
       * @return This builder for chaining.
       */
      public Builder setNetPrice(double value) {
        
        netPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       *净价
       * </pre>
       *
       * <code>double net_price = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetPrice() {
        
        netPrice_ = 0D;
        onChanged();
        return this;
      }

      private double faceBalance_ ;
      /**
       * <pre>
       **
       * 券面总额
       * </pre>
       *
       * <code>double face_balance = 7;</code>
       * @return The faceBalance.
       */
      @java.lang.Override
      public double getFaceBalance() {
        return faceBalance_;
      }
      /**
       * <pre>
       **
       * 券面总额
       * </pre>
       *
       * <code>double face_balance = 7;</code>
       * @param value The faceBalance to set.
       * @return This builder for chaining.
       */
      public Builder setFaceBalance(double value) {
        
        faceBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 券面总额
       * </pre>
       *
       * <code>double face_balance = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaceBalance() {
        
        faceBalance_ = 0D;
        onChanged();
        return this;
      }

      private int validTime_ ;
      /**
       * <pre>
       **
       * 有效时间
       * </pre>
       *
       * <code>int32 valid_time = 8;</code>
       * @return Whether the validTime field is set.
       */
      @java.lang.Override
      public boolean hasValidTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       **
       * 有效时间
       * </pre>
       *
       * <code>int32 valid_time = 8;</code>
       * @return The validTime.
       */
      @java.lang.Override
      public int getValidTime() {
        return validTime_;
      }
      /**
       * <pre>
       **
       * 有效时间
       * </pre>
       *
       * <code>int32 valid_time = 8;</code>
       * @param value The validTime to set.
       * @return This builder for chaining.
       */
      public Builder setValidTime(int value) {
        bitField0_ |= 0x00000001;
        validTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 有效时间
       * </pre>
       *
       * <code>int32 valid_time = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        validTime_ = 0;
        onChanged();
        return this;
      }

      private int extsystemId_ ;
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 9;</code>
       * @return Whether the extsystemId field is set.
       */
      @java.lang.Override
      public boolean hasExtsystemId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 9;</code>
       * @return The extsystemId.
       */
      @java.lang.Override
      public int getExtsystemId() {
        return extsystemId_;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 9;</code>
       * @param value The extsystemId to set.
       * @return This builder for chaining.
       */
      public Builder setExtsystemId(int value) {
        bitField0_ |= 0x00000002;
        extsystemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtsystemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        extsystemId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object thirdReff_ = "";
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 10;</code>
       * @return Whether the thirdReff field is set.
       */
      public boolean hasThirdReff() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 10;</code>
       * @return The thirdReff.
       */
      public java.lang.String getThirdReff() {
        java.lang.Object ref = thirdReff_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          thirdReff_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 10;</code>
       * @return The bytes for thirdReff.
       */
      public com.google.protobuf.ByteString
          getThirdReffBytes() {
        java.lang.Object ref = thirdReff_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thirdReff_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 10;</code>
       * @param value The thirdReff to set.
       * @return This builder for chaining.
       */
      public Builder setThirdReff(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        thirdReff_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearThirdReff() {
        bitField0_ = (bitField0_ & ~0x00000004);
        thirdReff_ = getDefaultInstance().getThirdReff();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 10;</code>
       * @param value The bytes for thirdReff to set.
       * @return This builder for chaining.
       */
      public Builder setThirdReffBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        thirdReff_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BankMtkRequest)
    }

    // @@protoc_insertion_point(class_scope:BankMtkRequest)
    private static final SubscribeReq.BankMtkRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SubscribeReq.BankMtkRequest();
    }

    public static SubscribeReq.BankMtkRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BankMtkRequest>
        PARSER = new com.google.protobuf.AbstractParser<BankMtkRequest>() {
      @java.lang.Override
      public BankMtkRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BankMtkRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BankMtkRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BankMtkRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SubscribeReq.BankMtkRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BankMtkRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BankMtkRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SubscribeReq.proto\"\243\002\n\016BankMtkRequest\022" +
      "\024\n\014account_code\030\001 \001(\t\022\020\n\010combi_no\030\002 \001(\t\022" +
      "\023\n\013invest_type\030\003 \001(\t\022\022\n\nrequest_id\030\004 \001(\t" +
      "\022\033\n\023owner_operator_name\030\005 \001(\t\022\021\n\tnet_pri" +
      "ce\030\006 \001(\001\022\024\n\014face_balance\030\007 \001(\001\022\027\n\nvalid_" +
      "time\030\010 \001(\005H\000\210\001\001\022\031\n\014extsystem_id\030\t \001(\005H\001\210" +
      "\001\001\022\027\n\nthird_reff\030\n \001(\tH\002\210\001\001B\r\n\013_valid_ti" +
      "meB\017\n\r_extsystem_idB\r\n\013_third_reffB:\n*co" +
      "m.sumscope.qt.cbt.connector.ufx.protobuf" +
      "B\014SubscribeReqb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BankMtkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BankMtkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BankMtkRequest_descriptor,
        new java.lang.String[] { "AccountCode", "CombiNo", "InvestType", "RequestId", "OwnerOperatorName", "NetPrice", "FaceBalance", "ValidTime", "ExtsystemId", "ThirdReff", "ValidTime", "ExtsystemId", "ThirdReff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
