// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResp.proto

package com.sumscope.qt.cbt.connector.ufx.protobuf.entity;

public final class SubscribeResp {
  private SubscribeResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BankMtkRequestRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BankMtkRequestResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 第三方系统自定义号
     * </pre>
     *
     * <code>int32 extsystem_id = 1;</code>
     * @return The extsystemId.
     */
    int getExtsystemId();

    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 2;</code>
     * @return The thirdReff.
     */
    java.lang.String getThirdReff();
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 2;</code>
     * @return The bytes for thirdReff.
     */
    com.google.protobuf.ByteString
        getThirdReffBytes();

    /**
     * <pre>
     **
     * 委托序号
     * </pre>
     *
     * <code>int32 entrust_no = 3;</code>
     * @return The entrustNo.
     */
    int getEntrustNo();

    /**
     * <pre>
     **
     * 委托失败代码
     * </pre>
     *
     * <code>int32 entrust_fail_code = 4;</code>
     * @return The entrustFailCode.
     */
    int getEntrustFailCode();

    /**
     * <pre>
     **
     * 失败原因
     * </pre>
     *
     * <code>string fail_cause = 5;</code>
     * @return The failCause.
     */
    java.lang.String getFailCause();
    /**
     * <pre>
     **
     * 失败原因
     * </pre>
     *
     * <code>string fail_cause = 5;</code>
     * @return The bytes for failCause.
     */
    com.google.protobuf.ByteString
        getFailCauseBytes();

    /**
     * <pre>
     **
     * 风控判断流水号
     * </pre>
     *
     * <code>int32 risk_serial_no = 6;</code>
     * @return The riskSerialNo.
     */
    int getRiskSerialNo();

    /**
     * <pre>
     **
     * 证券代码
     * </pre>
     *
     * <code>string stock_code = 7;</code>
     * @return The stockCode.
     */
    java.lang.String getStockCode();
    /**
     * <pre>
     **
     * 证券代码
     * </pre>
     *
     * <code>string stock_code = 7;</code>
     * @return The bytes for stockCode.
     */
    com.google.protobuf.ByteString
        getStockCodeBytes();

    /**
     * <pre>
     **
     * 委托方向
     * </pre>
     *
     * <code>string entrust_direction = 8;</code>
     * @return The entrustDirection.
     */
    java.lang.String getEntrustDirection();
    /**
     * <pre>
     **
     * 委托方向
     * </pre>
     *
     * <code>string entrust_direction = 8;</code>
     * @return The bytes for entrustDirection.
     */
    com.google.protobuf.ByteString
        getEntrustDirectionBytes();

    /**
     * <pre>
     **
     * 风控序号
     * </pre>
     *
     * <code>int32 risk_no = 9;</code>
     * @return The riskNo.
     */
    int getRiskNo();

    /**
     * <pre>
     **
     * 风控类型
     * </pre>
     *
     * <code>string risk_type = 10;</code>
     * @return The riskType.
     */
    java.lang.String getRiskType();
    /**
     * <pre>
     **
     * 风控类型
     * </pre>
     *
     * <code>string risk_type = 10;</code>
     * @return The bytes for riskType.
     */
    com.google.protobuf.ByteString
        getRiskTypeBytes();

    /**
     * <pre>
     **
     * 风控说明
     * </pre>
     *
     * <code>string risk_summary = 11;</code>
     * @return The riskSummary.
     */
    java.lang.String getRiskSummary();
    /**
     * <pre>
     **
     * 风控说明
     * </pre>
     *
     * <code>string risk_summary = 11;</code>
     * @return The bytes for riskSummary.
     */
    com.google.protobuf.ByteString
        getRiskSummaryBytes();

    /**
     * <pre>
     **
     * 风控触警操作
     * </pre>
     *
     * <code>string risk_operation = 12;</code>
     * @return The riskOperation.
     */
    java.lang.String getRiskOperation();
    /**
     * <pre>
     **
     * 风控触警操作
     * </pre>
     *
     * <code>string risk_operation = 12;</code>
     * @return The bytes for riskOperation.
     */
    com.google.protobuf.ByteString
        getRiskOperationBytes();

    /**
     * <pre>
     **
     * 风控触发风控说明
     * </pre>
     *
     * <code>string remark_short = 13;</code>
     * @return The remarkShort.
     */
    java.lang.String getRemarkShort();
    /**
     * <pre>
     **
     * 风控触发风控说明
     * </pre>
     *
     * <code>string remark_short = 13;</code>
     * @return The bytes for remarkShort.
     */
    com.google.protobuf.ByteString
        getRemarkShortBytes();

    /**
     * <pre>
     **
     * 风控阀值
     * </pre>
     *
     * <code>double risk_threshold_value = 14;</code>
     * @return The riskThresholdValue.
     */
    double getRiskThresholdValue();

    /**
     * <pre>
     **
     * 风控计算值
     * </pre>
     *
     * <code>double risk_value = 15;</code>
     * @return The riskValue.
     */
    double getRiskValue();
  }
  /**
   * <pre>
   *银行间做市请求回复委托				
   * </pre>
   *
   * Protobuf type {@code BankMtkRequestResp}
   */
  public static final class BankMtkRequestResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BankMtkRequestResp)
      BankMtkRequestRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BankMtkRequestResp.newBuilder() to construct.
    private BankMtkRequestResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BankMtkRequestResp() {
      thirdReff_ = "";
      failCause_ = "";
      stockCode_ = "";
      entrustDirection_ = "";
      riskType_ = "";
      riskSummary_ = "";
      riskOperation_ = "";
      remarkShort_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BankMtkRequestResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BankMtkRequestResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              extsystemId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              thirdReff_ = s;
              break;
            }
            case 24: {

              entrustNo_ = input.readInt32();
              break;
            }
            case 32: {

              entrustFailCode_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              failCause_ = s;
              break;
            }
            case 48: {

              riskSerialNo_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              stockCode_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              entrustDirection_ = s;
              break;
            }
            case 72: {

              riskNo_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              riskType_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              riskSummary_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              riskOperation_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              remarkShort_ = s;
              break;
            }
            case 113: {

              riskThresholdValue_ = input.readDouble();
              break;
            }
            case 121: {

              riskValue_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscribeResp.internal_static_BankMtkRequestResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscribeResp.internal_static_BankMtkRequestResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscribeResp.BankMtkRequestResp.class, SubscribeResp.BankMtkRequestResp.Builder.class);
    }

    public static final int EXTSYSTEM_ID_FIELD_NUMBER = 1;
    private int extsystemId_;
    /**
     * <pre>
     **
     * 第三方系统自定义号
     * </pre>
     *
     * <code>int32 extsystem_id = 1;</code>
     * @return The extsystemId.
     */
    @java.lang.Override
    public int getExtsystemId() {
      return extsystemId_;
    }

    public static final int THIRD_REFF_FIELD_NUMBER = 2;
    private volatile java.lang.Object thirdReff_;
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 2;</code>
     * @return The thirdReff.
     */
    @java.lang.Override
    public java.lang.String getThirdReff() {
      java.lang.Object ref = thirdReff_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        thirdReff_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 第三方系统自定义说明
     * </pre>
     *
     * <code>string third_reff = 2;</code>
     * @return The bytes for thirdReff.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThirdReffBytes() {
      java.lang.Object ref = thirdReff_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thirdReff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTRUST_NO_FIELD_NUMBER = 3;
    private int entrustNo_;
    /**
     * <pre>
     **
     * 委托序号
     * </pre>
     *
     * <code>int32 entrust_no = 3;</code>
     * @return The entrustNo.
     */
    @java.lang.Override
    public int getEntrustNo() {
      return entrustNo_;
    }

    public static final int ENTRUST_FAIL_CODE_FIELD_NUMBER = 4;
    private int entrustFailCode_;
    /**
     * <pre>
     **
     * 委托失败代码
     * </pre>
     *
     * <code>int32 entrust_fail_code = 4;</code>
     * @return The entrustFailCode.
     */
    @java.lang.Override
    public int getEntrustFailCode() {
      return entrustFailCode_;
    }

    public static final int FAIL_CAUSE_FIELD_NUMBER = 5;
    private volatile java.lang.Object failCause_;
    /**
     * <pre>
     **
     * 失败原因
     * </pre>
     *
     * <code>string fail_cause = 5;</code>
     * @return The failCause.
     */
    @java.lang.Override
    public java.lang.String getFailCause() {
      java.lang.Object ref = failCause_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        failCause_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 失败原因
     * </pre>
     *
     * <code>string fail_cause = 5;</code>
     * @return The bytes for failCause.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFailCauseBytes() {
      java.lang.Object ref = failCause_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        failCause_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RISK_SERIAL_NO_FIELD_NUMBER = 6;
    private int riskSerialNo_;
    /**
     * <pre>
     **
     * 风控判断流水号
     * </pre>
     *
     * <code>int32 risk_serial_no = 6;</code>
     * @return The riskSerialNo.
     */
    @java.lang.Override
    public int getRiskSerialNo() {
      return riskSerialNo_;
    }

    public static final int STOCK_CODE_FIELD_NUMBER = 7;
    private volatile java.lang.Object stockCode_;
    /**
     * <pre>
     **
     * 证券代码
     * </pre>
     *
     * <code>string stock_code = 7;</code>
     * @return The stockCode.
     */
    @java.lang.Override
    public java.lang.String getStockCode() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 证券代码
     * </pre>
     *
     * <code>string stock_code = 7;</code>
     * @return The bytes for stockCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStockCodeBytes() {
      java.lang.Object ref = stockCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTRUST_DIRECTION_FIELD_NUMBER = 8;
    private volatile java.lang.Object entrustDirection_;
    /**
     * <pre>
     **
     * 委托方向
     * </pre>
     *
     * <code>string entrust_direction = 8;</code>
     * @return The entrustDirection.
     */
    @java.lang.Override
    public java.lang.String getEntrustDirection() {
      java.lang.Object ref = entrustDirection_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entrustDirection_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 委托方向
     * </pre>
     *
     * <code>string entrust_direction = 8;</code>
     * @return The bytes for entrustDirection.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEntrustDirectionBytes() {
      java.lang.Object ref = entrustDirection_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entrustDirection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RISK_NO_FIELD_NUMBER = 9;
    private int riskNo_;
    /**
     * <pre>
     **
     * 风控序号
     * </pre>
     *
     * <code>int32 risk_no = 9;</code>
     * @return The riskNo.
     */
    @java.lang.Override
    public int getRiskNo() {
      return riskNo_;
    }

    public static final int RISK_TYPE_FIELD_NUMBER = 10;
    private volatile java.lang.Object riskType_;
    /**
     * <pre>
     **
     * 风控类型
     * </pre>
     *
     * <code>string risk_type = 10;</code>
     * @return The riskType.
     */
    @java.lang.Override
    public java.lang.String getRiskType() {
      java.lang.Object ref = riskType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        riskType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 风控类型
     * </pre>
     *
     * <code>string risk_type = 10;</code>
     * @return The bytes for riskType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRiskTypeBytes() {
      java.lang.Object ref = riskType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        riskType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RISK_SUMMARY_FIELD_NUMBER = 11;
    private volatile java.lang.Object riskSummary_;
    /**
     * <pre>
     **
     * 风控说明
     * </pre>
     *
     * <code>string risk_summary = 11;</code>
     * @return The riskSummary.
     */
    @java.lang.Override
    public java.lang.String getRiskSummary() {
      java.lang.Object ref = riskSummary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        riskSummary_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 风控说明
     * </pre>
     *
     * <code>string risk_summary = 11;</code>
     * @return The bytes for riskSummary.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRiskSummaryBytes() {
      java.lang.Object ref = riskSummary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        riskSummary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RISK_OPERATION_FIELD_NUMBER = 12;
    private volatile java.lang.Object riskOperation_;
    /**
     * <pre>
     **
     * 风控触警操作
     * </pre>
     *
     * <code>string risk_operation = 12;</code>
     * @return The riskOperation.
     */
    @java.lang.Override
    public java.lang.String getRiskOperation() {
      java.lang.Object ref = riskOperation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        riskOperation_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 风控触警操作
     * </pre>
     *
     * <code>string risk_operation = 12;</code>
     * @return The bytes for riskOperation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRiskOperationBytes() {
      java.lang.Object ref = riskOperation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        riskOperation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_SHORT_FIELD_NUMBER = 13;
    private volatile java.lang.Object remarkShort_;
    /**
     * <pre>
     **
     * 风控触发风控说明
     * </pre>
     *
     * <code>string remark_short = 13;</code>
     * @return The remarkShort.
     */
    @java.lang.Override
    public java.lang.String getRemarkShort() {
      java.lang.Object ref = remarkShort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remarkShort_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 风控触发风控说明
     * </pre>
     *
     * <code>string remark_short = 13;</code>
     * @return The bytes for remarkShort.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemarkShortBytes() {
      java.lang.Object ref = remarkShort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remarkShort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RISK_THRESHOLD_VALUE_FIELD_NUMBER = 14;
    private double riskThresholdValue_;
    /**
     * <pre>
     **
     * 风控阀值
     * </pre>
     *
     * <code>double risk_threshold_value = 14;</code>
     * @return The riskThresholdValue.
     */
    @java.lang.Override
    public double getRiskThresholdValue() {
      return riskThresholdValue_;
    }

    public static final int RISK_VALUE_FIELD_NUMBER = 15;
    private double riskValue_;
    /**
     * <pre>
     **
     * 风控计算值
     * </pre>
     *
     * <code>double risk_value = 15;</code>
     * @return The riskValue.
     */
    @java.lang.Override
    public double getRiskValue() {
      return riskValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (extsystemId_ != 0) {
        output.writeInt32(1, extsystemId_);
      }
      if (!getThirdReffBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, thirdReff_);
      }
      if (entrustNo_ != 0) {
        output.writeInt32(3, entrustNo_);
      }
      if (entrustFailCode_ != 0) {
        output.writeInt32(4, entrustFailCode_);
      }
      if (!getFailCauseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, failCause_);
      }
      if (riskSerialNo_ != 0) {
        output.writeInt32(6, riskSerialNo_);
      }
      if (!getStockCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, stockCode_);
      }
      if (!getEntrustDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, entrustDirection_);
      }
      if (riskNo_ != 0) {
        output.writeInt32(9, riskNo_);
      }
      if (!getRiskTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, riskType_);
      }
      if (!getRiskSummaryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, riskSummary_);
      }
      if (!getRiskOperationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, riskOperation_);
      }
      if (!getRemarkShortBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, remarkShort_);
      }
      if (riskThresholdValue_ != 0D) {
        output.writeDouble(14, riskThresholdValue_);
      }
      if (riskValue_ != 0D) {
        output.writeDouble(15, riskValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (extsystemId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, extsystemId_);
      }
      if (!getThirdReffBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, thirdReff_);
      }
      if (entrustNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, entrustNo_);
      }
      if (entrustFailCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, entrustFailCode_);
      }
      if (!getFailCauseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, failCause_);
      }
      if (riskSerialNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, riskSerialNo_);
      }
      if (!getStockCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, stockCode_);
      }
      if (!getEntrustDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, entrustDirection_);
      }
      if (riskNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, riskNo_);
      }
      if (!getRiskTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, riskType_);
      }
      if (!getRiskSummaryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, riskSummary_);
      }
      if (!getRiskOperationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, riskOperation_);
      }
      if (!getRemarkShortBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, remarkShort_);
      }
      if (riskThresholdValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, riskThresholdValue_);
      }
      if (riskValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, riskValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SubscribeResp.BankMtkRequestResp)) {
        return super.equals(obj);
      }
      SubscribeResp.BankMtkRequestResp other = (SubscribeResp.BankMtkRequestResp) obj;

      if (getExtsystemId()
          != other.getExtsystemId()) return false;
      if (!getThirdReff()
          .equals(other.getThirdReff())) return false;
      if (getEntrustNo()
          != other.getEntrustNo()) return false;
      if (getEntrustFailCode()
          != other.getEntrustFailCode()) return false;
      if (!getFailCause()
          .equals(other.getFailCause())) return false;
      if (getRiskSerialNo()
          != other.getRiskSerialNo()) return false;
      if (!getStockCode()
          .equals(other.getStockCode())) return false;
      if (!getEntrustDirection()
          .equals(other.getEntrustDirection())) return false;
      if (getRiskNo()
          != other.getRiskNo()) return false;
      if (!getRiskType()
          .equals(other.getRiskType())) return false;
      if (!getRiskSummary()
          .equals(other.getRiskSummary())) return false;
      if (!getRiskOperation()
          .equals(other.getRiskOperation())) return false;
      if (!getRemarkShort()
          .equals(other.getRemarkShort())) return false;
      if (java.lang.Double.doubleToLongBits(getRiskThresholdValue())
          != java.lang.Double.doubleToLongBits(
              other.getRiskThresholdValue())) return false;
      if (java.lang.Double.doubleToLongBits(getRiskValue())
          != java.lang.Double.doubleToLongBits(
              other.getRiskValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXTSYSTEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getExtsystemId();
      hash = (37 * hash) + THIRD_REFF_FIELD_NUMBER;
      hash = (53 * hash) + getThirdReff().hashCode();
      hash = (37 * hash) + ENTRUST_NO_FIELD_NUMBER;
      hash = (53 * hash) + getEntrustNo();
      hash = (37 * hash) + ENTRUST_FAIL_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getEntrustFailCode();
      hash = (37 * hash) + FAIL_CAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getFailCause().hashCode();
      hash = (37 * hash) + RISK_SERIAL_NO_FIELD_NUMBER;
      hash = (53 * hash) + getRiskSerialNo();
      hash = (37 * hash) + STOCK_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getStockCode().hashCode();
      hash = (37 * hash) + ENTRUST_DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getEntrustDirection().hashCode();
      hash = (37 * hash) + RISK_NO_FIELD_NUMBER;
      hash = (53 * hash) + getRiskNo();
      hash = (37 * hash) + RISK_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRiskType().hashCode();
      hash = (37 * hash) + RISK_SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getRiskSummary().hashCode();
      hash = (37 * hash) + RISK_OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getRiskOperation().hashCode();
      hash = (37 * hash) + REMARK_SHORT_FIELD_NUMBER;
      hash = (53 * hash) + getRemarkShort().hashCode();
      hash = (37 * hash) + RISK_THRESHOLD_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRiskThresholdValue()));
      hash = (37 * hash) + RISK_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRiskValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SubscribeResp.BankMtkRequestResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscribeResp.BankMtkRequestResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SubscribeResp.BankMtkRequestResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscribeResp.BankMtkRequestResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SubscribeResp.BankMtkRequestResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *银行间做市请求回复委托				
     * </pre>
     *
     * Protobuf type {@code BankMtkRequestResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BankMtkRequestResp)
        SubscribeResp.BankMtkRequestRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscribeResp.internal_static_BankMtkRequestResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscribeResp.internal_static_BankMtkRequestResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscribeResp.BankMtkRequestResp.class, SubscribeResp.BankMtkRequestResp.Builder.class);
      }

      // Construct using com.sumscope.qt.cbt.connector.ufx.protobuf.entity.SubscribeResp.BankMtkRequestResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        extsystemId_ = 0;

        thirdReff_ = "";

        entrustNo_ = 0;

        entrustFailCode_ = 0;

        failCause_ = "";

        riskSerialNo_ = 0;

        stockCode_ = "";

        entrustDirection_ = "";

        riskNo_ = 0;

        riskType_ = "";

        riskSummary_ = "";

        riskOperation_ = "";

        remarkShort_ = "";

        riskThresholdValue_ = 0D;

        riskValue_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscribeResp.internal_static_BankMtkRequestResp_descriptor;
      }

      @java.lang.Override
      public SubscribeResp.BankMtkRequestResp getDefaultInstanceForType() {
        return SubscribeResp.BankMtkRequestResp.getDefaultInstance();
      }

      @java.lang.Override
      public SubscribeResp.BankMtkRequestResp build() {
        SubscribeResp.BankMtkRequestResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SubscribeResp.BankMtkRequestResp buildPartial() {
        SubscribeResp.BankMtkRequestResp result = new SubscribeResp.BankMtkRequestResp(this);
        result.extsystemId_ = extsystemId_;
        result.thirdReff_ = thirdReff_;
        result.entrustNo_ = entrustNo_;
        result.entrustFailCode_ = entrustFailCode_;
        result.failCause_ = failCause_;
        result.riskSerialNo_ = riskSerialNo_;
        result.stockCode_ = stockCode_;
        result.entrustDirection_ = entrustDirection_;
        result.riskNo_ = riskNo_;
        result.riskType_ = riskType_;
        result.riskSummary_ = riskSummary_;
        result.riskOperation_ = riskOperation_;
        result.remarkShort_ = remarkShort_;
        result.riskThresholdValue_ = riskThresholdValue_;
        result.riskValue_ = riskValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SubscribeResp.BankMtkRequestResp) {
          return mergeFrom((SubscribeResp.BankMtkRequestResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SubscribeResp.BankMtkRequestResp other) {
        if (other == SubscribeResp.BankMtkRequestResp.getDefaultInstance()) return this;
        if (other.getExtsystemId() != 0) {
          setExtsystemId(other.getExtsystemId());
        }
        if (!other.getThirdReff().isEmpty()) {
          thirdReff_ = other.thirdReff_;
          onChanged();
        }
        if (other.getEntrustNo() != 0) {
          setEntrustNo(other.getEntrustNo());
        }
        if (other.getEntrustFailCode() != 0) {
          setEntrustFailCode(other.getEntrustFailCode());
        }
        if (!other.getFailCause().isEmpty()) {
          failCause_ = other.failCause_;
          onChanged();
        }
        if (other.getRiskSerialNo() != 0) {
          setRiskSerialNo(other.getRiskSerialNo());
        }
        if (!other.getStockCode().isEmpty()) {
          stockCode_ = other.stockCode_;
          onChanged();
        }
        if (!other.getEntrustDirection().isEmpty()) {
          entrustDirection_ = other.entrustDirection_;
          onChanged();
        }
        if (other.getRiskNo() != 0) {
          setRiskNo(other.getRiskNo());
        }
        if (!other.getRiskType().isEmpty()) {
          riskType_ = other.riskType_;
          onChanged();
        }
        if (!other.getRiskSummary().isEmpty()) {
          riskSummary_ = other.riskSummary_;
          onChanged();
        }
        if (!other.getRiskOperation().isEmpty()) {
          riskOperation_ = other.riskOperation_;
          onChanged();
        }
        if (!other.getRemarkShort().isEmpty()) {
          remarkShort_ = other.remarkShort_;
          onChanged();
        }
        if (other.getRiskThresholdValue() != 0D) {
          setRiskThresholdValue(other.getRiskThresholdValue());
        }
        if (other.getRiskValue() != 0D) {
          setRiskValue(other.getRiskValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SubscribeResp.BankMtkRequestResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SubscribeResp.BankMtkRequestResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int extsystemId_ ;
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 1;</code>
       * @return The extsystemId.
       */
      @java.lang.Override
      public int getExtsystemId() {
        return extsystemId_;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 1;</code>
       * @param value The extsystemId to set.
       * @return This builder for chaining.
       */
      public Builder setExtsystemId(int value) {
        
        extsystemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义号
       * </pre>
       *
       * <code>int32 extsystem_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtsystemId() {
        
        extsystemId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object thirdReff_ = "";
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 2;</code>
       * @return The thirdReff.
       */
      public java.lang.String getThirdReff() {
        java.lang.Object ref = thirdReff_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          thirdReff_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 2;</code>
       * @return The bytes for thirdReff.
       */
      public com.google.protobuf.ByteString
          getThirdReffBytes() {
        java.lang.Object ref = thirdReff_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thirdReff_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 2;</code>
       * @param value The thirdReff to set.
       * @return This builder for chaining.
       */
      public Builder setThirdReff(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        thirdReff_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearThirdReff() {
        
        thirdReff_ = getDefaultInstance().getThirdReff();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 第三方系统自定义说明
       * </pre>
       *
       * <code>string third_reff = 2;</code>
       * @param value The bytes for thirdReff to set.
       * @return This builder for chaining.
       */
      public Builder setThirdReffBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        thirdReff_ = value;
        onChanged();
        return this;
      }

      private int entrustNo_ ;
      /**
       * <pre>
       **
       * 委托序号
       * </pre>
       *
       * <code>int32 entrust_no = 3;</code>
       * @return The entrustNo.
       */
      @java.lang.Override
      public int getEntrustNo() {
        return entrustNo_;
      }
      /**
       * <pre>
       **
       * 委托序号
       * </pre>
       *
       * <code>int32 entrust_no = 3;</code>
       * @param value The entrustNo to set.
       * @return This builder for chaining.
       */
      public Builder setEntrustNo(int value) {
        
        entrustNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 委托序号
       * </pre>
       *
       * <code>int32 entrust_no = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntrustNo() {
        
        entrustNo_ = 0;
        onChanged();
        return this;
      }

      private int entrustFailCode_ ;
      /**
       * <pre>
       **
       * 委托失败代码
       * </pre>
       *
       * <code>int32 entrust_fail_code = 4;</code>
       * @return The entrustFailCode.
       */
      @java.lang.Override
      public int getEntrustFailCode() {
        return entrustFailCode_;
      }
      /**
       * <pre>
       **
       * 委托失败代码
       * </pre>
       *
       * <code>int32 entrust_fail_code = 4;</code>
       * @param value The entrustFailCode to set.
       * @return This builder for chaining.
       */
      public Builder setEntrustFailCode(int value) {
        
        entrustFailCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 委托失败代码
       * </pre>
       *
       * <code>int32 entrust_fail_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntrustFailCode() {
        
        entrustFailCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object failCause_ = "";
      /**
       * <pre>
       **
       * 失败原因
       * </pre>
       *
       * <code>string fail_cause = 5;</code>
       * @return The failCause.
       */
      public java.lang.String getFailCause() {
        java.lang.Object ref = failCause_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          failCause_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 失败原因
       * </pre>
       *
       * <code>string fail_cause = 5;</code>
       * @return The bytes for failCause.
       */
      public com.google.protobuf.ByteString
          getFailCauseBytes() {
        java.lang.Object ref = failCause_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          failCause_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 失败原因
       * </pre>
       *
       * <code>string fail_cause = 5;</code>
       * @param value The failCause to set.
       * @return This builder for chaining.
       */
      public Builder setFailCause(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        failCause_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 失败原因
       * </pre>
       *
       * <code>string fail_cause = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFailCause() {
        
        failCause_ = getDefaultInstance().getFailCause();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 失败原因
       * </pre>
       *
       * <code>string fail_cause = 5;</code>
       * @param value The bytes for failCause to set.
       * @return This builder for chaining.
       */
      public Builder setFailCauseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        failCause_ = value;
        onChanged();
        return this;
      }

      private int riskSerialNo_ ;
      /**
       * <pre>
       **
       * 风控判断流水号
       * </pre>
       *
       * <code>int32 risk_serial_no = 6;</code>
       * @return The riskSerialNo.
       */
      @java.lang.Override
      public int getRiskSerialNo() {
        return riskSerialNo_;
      }
      /**
       * <pre>
       **
       * 风控判断流水号
       * </pre>
       *
       * <code>int32 risk_serial_no = 6;</code>
       * @param value The riskSerialNo to set.
       * @return This builder for chaining.
       */
      public Builder setRiskSerialNo(int value) {
        
        riskSerialNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控判断流水号
       * </pre>
       *
       * <code>int32 risk_serial_no = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskSerialNo() {
        
        riskSerialNo_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stockCode_ = "";
      /**
       * <pre>
       **
       * 证券代码
       * </pre>
       *
       * <code>string stock_code = 7;</code>
       * @return The stockCode.
       */
      public java.lang.String getStockCode() {
        java.lang.Object ref = stockCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 证券代码
       * </pre>
       *
       * <code>string stock_code = 7;</code>
       * @return The bytes for stockCode.
       */
      public com.google.protobuf.ByteString
          getStockCodeBytes() {
        java.lang.Object ref = stockCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 证券代码
       * </pre>
       *
       * <code>string stock_code = 7;</code>
       * @param value The stockCode to set.
       * @return This builder for chaining.
       */
      public Builder setStockCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 证券代码
       * </pre>
       *
       * <code>string stock_code = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStockCode() {
        
        stockCode_ = getDefaultInstance().getStockCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 证券代码
       * </pre>
       *
       * <code>string stock_code = 7;</code>
       * @param value The bytes for stockCode to set.
       * @return This builder for chaining.
       */
      public Builder setStockCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stockCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object entrustDirection_ = "";
      /**
       * <pre>
       **
       * 委托方向
       * </pre>
       *
       * <code>string entrust_direction = 8;</code>
       * @return The entrustDirection.
       */
      public java.lang.String getEntrustDirection() {
        java.lang.Object ref = entrustDirection_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          entrustDirection_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 委托方向
       * </pre>
       *
       * <code>string entrust_direction = 8;</code>
       * @return The bytes for entrustDirection.
       */
      public com.google.protobuf.ByteString
          getEntrustDirectionBytes() {
        java.lang.Object ref = entrustDirection_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entrustDirection_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 委托方向
       * </pre>
       *
       * <code>string entrust_direction = 8;</code>
       * @param value The entrustDirection to set.
       * @return This builder for chaining.
       */
      public Builder setEntrustDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        entrustDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 委托方向
       * </pre>
       *
       * <code>string entrust_direction = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntrustDirection() {
        
        entrustDirection_ = getDefaultInstance().getEntrustDirection();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 委托方向
       * </pre>
       *
       * <code>string entrust_direction = 8;</code>
       * @param value The bytes for entrustDirection to set.
       * @return This builder for chaining.
       */
      public Builder setEntrustDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        entrustDirection_ = value;
        onChanged();
        return this;
      }

      private int riskNo_ ;
      /**
       * <pre>
       **
       * 风控序号
       * </pre>
       *
       * <code>int32 risk_no = 9;</code>
       * @return The riskNo.
       */
      @java.lang.Override
      public int getRiskNo() {
        return riskNo_;
      }
      /**
       * <pre>
       **
       * 风控序号
       * </pre>
       *
       * <code>int32 risk_no = 9;</code>
       * @param value The riskNo to set.
       * @return This builder for chaining.
       */
      public Builder setRiskNo(int value) {
        
        riskNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控序号
       * </pre>
       *
       * <code>int32 risk_no = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskNo() {
        
        riskNo_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object riskType_ = "";
      /**
       * <pre>
       **
       * 风控类型
       * </pre>
       *
       * <code>string risk_type = 10;</code>
       * @return The riskType.
       */
      public java.lang.String getRiskType() {
        java.lang.Object ref = riskType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          riskType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控类型
       * </pre>
       *
       * <code>string risk_type = 10;</code>
       * @return The bytes for riskType.
       */
      public com.google.protobuf.ByteString
          getRiskTypeBytes() {
        java.lang.Object ref = riskType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          riskType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控类型
       * </pre>
       *
       * <code>string risk_type = 10;</code>
       * @param value The riskType to set.
       * @return This builder for chaining.
       */
      public Builder setRiskType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        riskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控类型
       * </pre>
       *
       * <code>string risk_type = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskType() {
        
        riskType_ = getDefaultInstance().getRiskType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控类型
       * </pre>
       *
       * <code>string risk_type = 10;</code>
       * @param value The bytes for riskType to set.
       * @return This builder for chaining.
       */
      public Builder setRiskTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        riskType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object riskSummary_ = "";
      /**
       * <pre>
       **
       * 风控说明
       * </pre>
       *
       * <code>string risk_summary = 11;</code>
       * @return The riskSummary.
       */
      public java.lang.String getRiskSummary() {
        java.lang.Object ref = riskSummary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          riskSummary_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控说明
       * </pre>
       *
       * <code>string risk_summary = 11;</code>
       * @return The bytes for riskSummary.
       */
      public com.google.protobuf.ByteString
          getRiskSummaryBytes() {
        java.lang.Object ref = riskSummary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          riskSummary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控说明
       * </pre>
       *
       * <code>string risk_summary = 11;</code>
       * @param value The riskSummary to set.
       * @return This builder for chaining.
       */
      public Builder setRiskSummary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        riskSummary_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控说明
       * </pre>
       *
       * <code>string risk_summary = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskSummary() {
        
        riskSummary_ = getDefaultInstance().getRiskSummary();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控说明
       * </pre>
       *
       * <code>string risk_summary = 11;</code>
       * @param value The bytes for riskSummary to set.
       * @return This builder for chaining.
       */
      public Builder setRiskSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        riskSummary_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object riskOperation_ = "";
      /**
       * <pre>
       **
       * 风控触警操作
       * </pre>
       *
       * <code>string risk_operation = 12;</code>
       * @return The riskOperation.
       */
      public java.lang.String getRiskOperation() {
        java.lang.Object ref = riskOperation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          riskOperation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控触警操作
       * </pre>
       *
       * <code>string risk_operation = 12;</code>
       * @return The bytes for riskOperation.
       */
      public com.google.protobuf.ByteString
          getRiskOperationBytes() {
        java.lang.Object ref = riskOperation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          riskOperation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控触警操作
       * </pre>
       *
       * <code>string risk_operation = 12;</code>
       * @param value The riskOperation to set.
       * @return This builder for chaining.
       */
      public Builder setRiskOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        riskOperation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控触警操作
       * </pre>
       *
       * <code>string risk_operation = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskOperation() {
        
        riskOperation_ = getDefaultInstance().getRiskOperation();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控触警操作
       * </pre>
       *
       * <code>string risk_operation = 12;</code>
       * @param value The bytes for riskOperation to set.
       * @return This builder for chaining.
       */
      public Builder setRiskOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        riskOperation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remarkShort_ = "";
      /**
       * <pre>
       **
       * 风控触发风控说明
       * </pre>
       *
       * <code>string remark_short = 13;</code>
       * @return The remarkShort.
       */
      public java.lang.String getRemarkShort() {
        java.lang.Object ref = remarkShort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remarkShort_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控触发风控说明
       * </pre>
       *
       * <code>string remark_short = 13;</code>
       * @return The bytes for remarkShort.
       */
      public com.google.protobuf.ByteString
          getRemarkShortBytes() {
        java.lang.Object ref = remarkShort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remarkShort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 风控触发风控说明
       * </pre>
       *
       * <code>string remark_short = 13;</code>
       * @param value The remarkShort to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkShort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remarkShort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控触发风控说明
       * </pre>
       *
       * <code>string remark_short = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemarkShort() {
        
        remarkShort_ = getDefaultInstance().getRemarkShort();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控触发风控说明
       * </pre>
       *
       * <code>string remark_short = 13;</code>
       * @param value The bytes for remarkShort to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkShortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remarkShort_ = value;
        onChanged();
        return this;
      }

      private double riskThresholdValue_ ;
      /**
       * <pre>
       **
       * 风控阀值
       * </pre>
       *
       * <code>double risk_threshold_value = 14;</code>
       * @return The riskThresholdValue.
       */
      @java.lang.Override
      public double getRiskThresholdValue() {
        return riskThresholdValue_;
      }
      /**
       * <pre>
       **
       * 风控阀值
       * </pre>
       *
       * <code>double risk_threshold_value = 14;</code>
       * @param value The riskThresholdValue to set.
       * @return This builder for chaining.
       */
      public Builder setRiskThresholdValue(double value) {
        
        riskThresholdValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控阀值
       * </pre>
       *
       * <code>double risk_threshold_value = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskThresholdValue() {
        
        riskThresholdValue_ = 0D;
        onChanged();
        return this;
      }

      private double riskValue_ ;
      /**
       * <pre>
       **
       * 风控计算值
       * </pre>
       *
       * <code>double risk_value = 15;</code>
       * @return The riskValue.
       */
      @java.lang.Override
      public double getRiskValue() {
        return riskValue_;
      }
      /**
       * <pre>
       **
       * 风控计算值
       * </pre>
       *
       * <code>double risk_value = 15;</code>
       * @param value The riskValue to set.
       * @return This builder for chaining.
       */
      public Builder setRiskValue(double value) {
        
        riskValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 风控计算值
       * </pre>
       *
       * <code>double risk_value = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskValue() {
        
        riskValue_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BankMtkRequestResp)
    }

    // @@protoc_insertion_point(class_scope:BankMtkRequestResp)
    private static final SubscribeResp.BankMtkRequestResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SubscribeResp.BankMtkRequestResp();
    }

    public static SubscribeResp.BankMtkRequestResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BankMtkRequestResp>
        PARSER = new com.google.protobuf.AbstractParser<BankMtkRequestResp>() {
      @java.lang.Override
      public BankMtkRequestResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BankMtkRequestResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BankMtkRequestResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BankMtkRequestResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SubscribeResp.BankMtkRequestResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BankMtkRequestResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BankMtkRequestResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SubscribeResp.proto\"\342\002\n\022BankMtkRequest" +
      "Resp\022\024\n\014extsystem_id\030\001 \001(\005\022\022\n\nthird_reff" +
      "\030\002 \001(\t\022\022\n\nentrust_no\030\003 \001(\005\022\031\n\021entrust_fa" +
      "il_code\030\004 \001(\005\022\022\n\nfail_cause\030\005 \001(\t\022\026\n\016ris" +
      "k_serial_no\030\006 \001(\005\022\022\n\nstock_code\030\007 \001(\t\022\031\n" +
      "\021entrust_direction\030\010 \001(\t\022\017\n\007risk_no\030\t \001(" +
      "\005\022\021\n\trisk_type\030\n \001(\t\022\024\n\014risk_summary\030\013 \001" +
      "(\t\022\026\n\016risk_operation\030\014 \001(\t\022\024\n\014remark_sho" +
      "rt\030\r \001(\t\022\034\n\024risk_threshold_value\030\016 \001(\001\022\022" +
      "\n\nrisk_value\030\017 \001(\001B;\n*com.sumscope.qt.cb" +
      "t.connector.ufx.protobufB\rSubscribeRespb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BankMtkRequestResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BankMtkRequestResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BankMtkRequestResp_descriptor,
        new java.lang.String[] { "ExtsystemId", "ThirdReff", "EntrustNo", "EntrustFailCode", "FailCause", "RiskSerialNo", "StockCode", "EntrustDirection", "RiskNo", "RiskType", "RiskSummary", "RiskOperation", "RemarkShort", "RiskThresholdValue", "RiskValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
